 const allSkills = [
    {
        id:0,
        name:'Html 5',
        img:'/../public/assets/skills/html.png'
    },
    {
        id:1,
        name:'Css 3',
        img:'/../public/assets/skills/css.png'
    },
    {
        id:1,
        name:'Javascript',
        img:'/../public/assets/skills/javascript.png'
    },
    {
        id:2,
        name:'React',
        img:'/../public/assets/skills/react.png'
    },
    {
        id:3,
        name:'Redux',
        img:'/../public/assets/skills/redux.png'
    },
    {
        id:3,
        name:'Next.js',
        img:'/../public/assets/skills/nextjs.png'
    },
    {
        id:4,
        name:'Remix',
        img:'/../public/assets/skills/remix.png'
    },
    {
        id:5,
        name:'Bootstrap 5',
        img:'/../public/assets/skills/bootstrap.png'
    },
    {
        id:6,
        name:'Sass/Scss',
        img:'/../public/assets/skills/sass.png'
    },
    {
        id:7,
        name:'Tailwindcss',
        img:'/../public/assets/skills/tailwind.png'
    },
    {
        id:8,
        name:'Firebase',
        img:'/../public/assets/skills/firebase.png'
    },
    {
        id:9,
        name:'Strapi',
        img:'/../public/assets/skills/strapi.png'
    },
    {
        id:10,
        name:'Github',
        img:'/../public/assets/skills/github1.png'
    },
    {
        id:11,
        name:'Git',
        img:'/../public/assets/skills/git.png'
    },
]

export default allSkills 